DATA:
  data_root: /home/LAB/r-yanghongyu/data/cityscapes
  train_list: data/cityscapes/list/fine_train.txt
  val_list: data/cityscapes/list/fine_val.txt
  classes: 19

TRAIN:
  arch: bcanet
  layers: 50
  sync_bn: True  # adopt syncbn or not
  train_h: 769
  train_w: 769
  multi_grid: [1,1,1]
  ohem: False
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  seg_weight: 1.0
  edge_weight: 1.0
  att_weight: 1.0
  aux_weight: 0.4
  train_gpu: [0,1]
  workers: 8  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 4  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 200
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0005
  manual_seed:
  print_freq: 10
  save_freq: 1
  val_freq: 1
  save_path: exp/cityscapes/bcanet50/model
  weight:    # path to initial weight (default: none)
  resume:   # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6770
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: False
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  test_list: data/cityscapes/list/fine_val.txt
  split: val  # split in [train, val and test]
  base_size: 2048  # based size for scaling
  test_h: 769
  test_w: 769
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: exp/cityscapes/bcanet50/model/train_epoch_200.pth  # evaluation model path
  save_folder: exp/cityscapes/bcanet50/val/ss # results save folder
  colors_path: data/cityscapes/cityscapes_colors.txt  # path of dataset colors
  names_path: data/cityscapes/cityscapes_names.txt  # path of dataset category names